FROM mysql:5.7 AS nuxt.db.bouwenergie.local
EXPOSE 3306 3306

# RUN chmod 0444 /etc/mysql/mysql.conf.d/mysqld.cnf
# RUN chmod 0444 /var/local/platform.bouwenergie.local/docker/platform-bouwenergie-local/db.bouwenergie.local/mysqld.cnf
# RUN chmod 0444 /etc/my.cnf.d/mariadb-server.cnf

# RUN yum update

# RUN yum -y install procps
# COPY docker-php-entrypoint /usr/local/bin

# RUN chmod +x /usr/local/bin/docker-php-entrypoint

# ENTRYPOINT [ "docker-php-entrypoint" ]

# WORKDIR /var/www
